# Default values for payment-service.

replicaCount: 1

image:
  repository: leonalessio/property-service   # Use your payment service image
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8006"
podLabels: {}

podSecurityContext: {}
securityContext: {}

actualSecrets: {}

service:
  type: ClusterIP
  port: 8006

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: hostflow.software
      paths:
        - path: /property(/|$)(.*)
          pathType: Prefix
  tls:
    - hosts:
        - hostflow.software
      secretName: property-tls

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules: []

resources: {}

livenessProbe:
  httpGet:
    path: /health/live
    port: 8006
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8006
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables for the payment service
env:
  ASPNETCORE_ENVIRONMENT: Development
  SwaggerPrefix: "/property"

# Secrets for sensitive information (mapped for .NET)
secrets:
  ConnectionStrings__Supabase:
    key: DB_URL_PROPERTY
  SupabaseStorage__Url:
    key: DB_URL_STORAGE
  SupabaseStorage__ServiceRoleKey:
    key: DB_SERVICE_ROLE_KEY
  SupabaseStorage__StorageBucket:
    key: DB_STORAGE_BUCKET