# Default values for payment-service.

replicaCount: 1

image:
  repository: leonalessio/payment-service   # Use your payment service image
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8007"
podLabels: {}

podSecurityContext: {}
securityContext: {}

actualSecrets: {}

service:
  type: ClusterIP
  port: 8007

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: hostflow.software
      paths:
        - path: /payment(/|$)(.*)
          pathType: Prefix
  tls:
    - hosts:
        - hostflow.software
      secretName: payment-tls

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules: []

resources: {}

livenessProbe:
  httpGet:
    path: /health/live
    port: 8007
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8007
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables for the payment service
env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_PATHBASE: "/payment"
  Kafka__BootstrapServers: "pkc-56d1g.eastus.azure.confluent.cloud:9092"
  Kafka__ClientId: "payment-service"
  Kafka__PaymentsTopic: "booking.payments"

# Secrets for sensitive information (mapped for .NET)
secrets:
  ConnectionStrings__Supabase:
    key: DB_URL_PAYMENT
  Stripe__ApiKey:
    key: STRIPE_KEY
  Stripe__WebhookSecret:
    key: STRIPE_WEBHOOK_SECRET
  Kafka__SaslMechanism:
    key: KAFKA_SASL_MECHANISM
  Kafka__SecurityProtocol:
    key: KAFKA_SECURITY_PROTOCOL
  Kafka__SaslUsername:
   key: KAFKA_SASL_USERNAME
  Kafka__SaslPassword:
    key: KAFKA_SASL_PASSWORD