# hostflow-umbrella/charts/profile-service/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "profile-secrets"
  name: profile-secrets
  labels:
    app: {{ include "profile-service.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ required "Database URL je obvezen!" .Values.actualSecrets.DATABASE_URL | b64enc | quote }}