# hostflow-umbrella/charts/payment-service/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "payment-secrets"
  name: payment-secrets
  labels:
    app: {{ include "payment-service.fullname" . }}
type: Opaque
data:
  # Zdaj beremo vrednosti iz .Values.actualSecrets, ki bodo nastavljene s --set v GitHub Actions
  STRIPE_KEY: {{ required "Stripe API Key je obvezen!" .Values.actualSecrets.STRIPE_KEY | b64enc | quote }}
  STRIPE_WEBHOOK_SECRET: {{ required "STRIPE_WEBHOOK_SECRET je obvezen!" .Values.actualSecrets.STRIPE_WEBHOOK_SECRET | b64enc | quote }}
  DB_URL_PAYMENT: {{ required "Database URL je obvezen!" .Values.actualSecrets.DB_URL_PAYMENT | b64enc | quote }}
  KAFKA_SASL_MECHANISM: {{ required "KAFKA_SASL_MECHANISM je obvezen!" .Values.actualSecrets.KAFKA_SASL_MECHANISM | b64enc | quote }}
  KAFKA_SECURITY_PROTOCOL: {{ required "KAFKA_SECURITY_PROTOCOL je obvezen!" .Values.actualSecrets.KAFKA_SECURITY_PROTOCOL | b64enc | quote }}
  KAFKA_SASL_USERNAME: {{ required "KAFKA_SASL_USERNAME je obvezen!" .Values.actualSecrets.KAFKA_SASL_USERNAME | b64enc | quote }}
  KAFKA_SASL_PASSWORD: {{ required "KAFKA_SASL_PASSWORD je obvezen!" .Values.actualSecrets.KAFKA_SASL_PASSWORD | b64enc | quote }}