# hostflow-umbrella/charts/payment-service/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "payment-secrets"
  name: payment-secrets
  labels:
    app: {{ include "payment-service.fullname" . }}
type: Opaque
data:
  # Zdaj beremo vrednosti iz .Values.actualSecrets, ki bodo nastavljene s --set v GitHub Actions
  STRIPE_API_KEY_VALUE: {{ required "Stripe API Key je obvezen!" .Values.actualSecrets.STRIPE_API_KEY | b64enc | quote }}
  DATABASE_URL_VALUE: {{ required "Database URL je obvezen!" .Values.actualSecrets.DATABASE_URL | b64enc | quote }}