# hostflow-umbrella/charts/payment-service/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "payment-secrets"
  name: payment-secrets
  labels:
    app: {{ include "payment-service.fullname" . }}
type: Opaque
data:
  # Base64 KODIRANE VREDNOSTI SO PRIDOBLEJNE IZ .Values.secrets
  STRIPE_API_KEY_VALUE: {{ required "Stripe API Key je obvezen!" .Values.secrets.STRIPE_API_KEY | b64enc | quote }}
  DATABASE_URL_VALUE: {{ required "Database URL je obvezen!" .Values.secrets.DATABASE_URL | b64enc | quote }}
  JWT_SECRET_VALUE: {{ required "JWT Secret je obvezen!" .Values.secrets.JWT_SECRET | b64enc | quote }}