# hostflow-umbrella/charts/booking-service/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "booking-secrets"
  name: booking-secrets
  labels:
    app: {{ include "booking-service.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ required "Database URL je obvezen!" .Values.actualSecrets.DATABASE_URL | b64enc | quote }}