# hostflow-umbrella/charts/payment-service/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "payment-secrets"
  name: payment-secrets
  labels:
    app: {{ include "payment-service.fullname" . }}
type: Opaque
data:
  DATABASE_URL_VALUE: {{ required "Database URL je obvezen!" .Values.actualSecrets.DATABASE_URL | b64enc | quote }}