payment-service:
  replicaCount: 1
  image:
    repository: tilen/payment-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8080
  env:
    APP_HOST: "0.0.0.0"
    APP_PORT: "8080"
    APP_NAME: "PaymentService"
    APP_VERSION: "1.0.0"
    APP_AUTHOR: "Tilen Anzeljc"
    LOG_LEVEL: "debug"
    ENVIRONMENT: "development"
  secrets:
    STRIPE_API_KEY:
      key: STRIPE_API_KEY_VALUE
    DATABASE_URL:
      key: DATABASE_URL_VALUE
    JWT_SECRET:
      key: JWT_SECRET_VALUE
service-b:
  replicaCount: 1
  image:
    repository: nginx
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8081
  env: {}

service-c:
  replicaCount: 1
  image:
    repository: nginx
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8082
  env: {}

service-d:
  replicaCount: 1
  image:
    repository: nginx
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8083
  env: {}

service-e:
  replicaCount: 1
  image:
    repository: nginx
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8084
  env: {}

service-f:
  replicaCount: 1
  image:
    repository: nginx
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8085
  env: {}

frontend:
  replicaCount: 1
  image:
    repository: nginx
    tag: dev
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
  env: {}
