# hostflow-umbrella/charts/booking-service/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "customer-secrets"
  name: communication-secrets
  labels:
    app: {{ include "communication-service.fullname" . }}
type: Opaque
data:
  MAILERSEND_API_KEY: {{ required "MAILERSEND_API_KEY URL required!" .Values.actualSecrets.MAILERSEND_API_KEY | b64enc | quote }}