apiVersion: v1
kind: Service
metadata:
<<<<<<<< HEAD:helm/charts/customer-service/templates/service.yaml
  name: {{ include "customer-service.fullname" . }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
========
  name: {{ include "communication-service.fullname" . }}
  labels:
    {{- include "communication-service.labels" . | nindent 4 }}
>>>>>>>> dev:helm/charts/communication-service/templates/service.yaml
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
<<<<<<<< HEAD:helm/charts/customer-service/templates/service.yaml
    {{- include "customer-service.selectorLabels" . | nindent 4 }}
========
    {{- include "communication-service.selectorLabels" . | nindent 4 }}
>>>>>>>> dev:helm/charts/communication-service/templates/service.yaml
