# hostflow-umbrella/charts/payment-service/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "payment-secrets"
  name: property-secrets
  labels:
    app: {{ include "property-service.fullname" . }}
type: Opaque
data:
  DB_SERVICE_ROLE_KEY: {{ required "DB_SERVICE_ROLE_KEY je obvezen!" .Values.actualSecrets.DB_SERVICE_ROLE_KEY | b64enc | quote }}
  DB_STORAGE_BUCKET: {{ required "DB_STORAGE_BUCKET je obvezen!" .Values.actualSecrets.DB_STORAGE_BUCKET | b64enc | quote }}
  DB_URL_PROPERTY: {{ required "DB_URL_PROPERTY je obvezen!" .Values.actualSecrets.DB_URL_PROPERTY | b64enc | quote }}
  DB_URL_STORAGE: {{ required "DB_URL_STORAGE je obvezen!" .Values.actualSecrets.DB_URL_STORAGE | b64enc | quote }}