# hostflow-umbrella/charts/booking-service/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "customer-secrets"
  name: customer-secrets
  labels:
    app: {{ include "customer-service.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ required "Database URL required!" .Values.actualSecrets.DATABASE_URL | b64enc | quote }}