# hostflow-umbrella/charts/booking-service/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  # Ime K8s Secreta mora biti "customer-secrets"
  name: customer-secrets
  labels:
    app: {{ include "customer-service.fullname" . }}
type: Opaque
data:
  HASHICORP_VAULT_ADDR: {{ required "HASHICORP_VAULT_TOKEN required!" .Values.actualSecrets.HASHICORP_VAULT_ADDR | b64enc | quote }}
  HASHICORP_VAULT_TOKEN: {{ required "HASHICORP_VAULT_TOKEN required!" .Values.actualSecrets.HASHICORP_VAULT_TOKEN | b64enc | quote }}
