basePath: /
definitions:
  invoice.CreateInvoiceRequest:
    properties:
      amount:
        type: number
      customer_id:
        type: string
      due_date:
        type: string
      invoice_number:
        type: string
      issue_date:
        description: ISO string, will parse in service
        type: string
      organization_id:
        type: string
      payment_id:
        type: string
      txt_amount:
        type: string
    type: object
  invoice.Invoice:
    properties:
      amount:
        type: number
      created_at:
        type: string
      customer_id:
        type: string
      due_date:
        type: string
      id:
        type: string
      invoice_number:
        type: string
      issue_date:
        type: string
      organization_id:
        type: string
      payment_id:
        description: nullable FK
        type: string
      txt_amount:
        type: string
    type: object
  invoice.UpdateInvoiceRequest:
    properties:
      amount:
        type: number
      customer_id:
        type: string
      due_date:
        type: string
      invoice_number:
        type: string
      issue_date:
        type: string
      payment_id:
        type: string
      txt_amount:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  payments.CreatePaymentRequest:
    properties:
      amount:
        type: integer
      currency:
        type: string
      description:
        type: string
      payment_method:
        type: string
    type: object
  payments.CreatePaymentResponse:
    properties:
      payment_intent_id:
        type: string
    type: object
  payments.Payment:
    properties:
      amount:
        type: number
      created_at:
        type: string
      id:
        type: string
      organization_id:
        type: string
      payment_intent_id:
        type: string
      payment_method:
        type: string
      reservation_id:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: Dokumentacija za Payment microservice
  title: Payment Service API
  version: "1.0"
paths:
  /invoices:
    get:
      description: Returns a list of all invoices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/invoice.Invoice'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all invoices
      tags:
      - invoices
    post:
      consumes:
      - application/json
      description: Creates a new invoice record
      parameters:
      - description: Invoice info
        in: body
        name: invoice
        required: true
        schema:
          $ref: '#/definitions/invoice.CreateInvoiceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/invoice.Invoice'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new invoice
      tags:
      - invoices
  /invoices/{id}:
    delete:
      description: Deletes an invoice by ID
      parameters:
      - description: Invoice ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete invoice
      tags:
      - invoices
    get:
      description: Returns an invoice based on ID
      parameters:
      - description: Invoice ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/invoice.Invoice'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get invoice by ID
      tags:
      - invoices
    put:
      consumes:
      - application/json
      description: Updates an existing invoice
      parameters:
      - description: Invoice ID
        in: path
        name: id
        required: true
        type: string
      - description: Invoice data
        in: body
        name: invoice
        required: true
        schema:
          $ref: '#/definitions/invoice.UpdateInvoiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/invoice.Invoice'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update an invoice
      tags:
      - invoices
  /payments:
    get:
      description: Returns a list of all payments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/payments.Payment'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all payments
      tags:
      - payments
    post:
      consumes:
      - application/json
      description: Creates a Stripe PaymentIntent with the given amount, currency,
        and description
      parameters:
      - description: Payment info
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/payments.CreatePaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payments.CreatePaymentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new payment
      tags:
      - payments
  /stripe/webhook:
    post:
      responses: {}
swagger: "2.0"
