on:
  push:
    branches:
      - actions-test
      - feature/metrics_property_payment
    paths:
      - "services/payment-service/**"
      - ".github/workflows/payment-service.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd services/payment-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install hostflow ./helm/charts/payment-service \
            --namespace default \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/payment-service \
            --set image.tag=latest \
            --set image.pullPolicy=Always \
            --set actualSecrets.STRIPE_API_KEY="${{ secrets.STRIPE_KEY }}" \
            --set actualSecrets.DATABASE_URL="${{ secrets.DB_URL_PAYMENT }}" \